package runner

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/google/uuid"
)

// Workspace is the per-request Sandbox_Job_Directory the architecture spec
// names. A Workspace is allocated once per accepted Code_Submission, owned
// exclusively by that request's lifecycle, and removed by Cleanup on every
// termination mode (architecture REQ A-24.3, REQ A-24.4).
//
// Construction is the only path that creates a Workspace value; callers
// MUST go through AllocateWorkspace so the recorded Path() and RequestID()
// remain trustworthy. Two callers that hand each other a *Workspace then
// receive the same view of the same on-disk directory; no other call can
// produce a value matching an existing Workspace's Path.
type Workspace struct {
	path      string
	requestID uuid.UUID
}

// Path returns the absolute on-disk path of the workspace.
//
// The string is filepath.Clean'd at construction time; it never changes
// after AllocateWorkspace returns. Verify uses byte-exact equality
// against this value to enforce architecture §11 "Workspace Isolation".
func (w *Workspace) Path() string { return w.path }

// RequestID returns the request identifier the workspace was allocated for.
//
// Wave C's orchestrator embeds the same id in structured log entries so
// reviewers can correlate a workspace path with the request that owned
// it.
func (w *Workspace) RequestID() uuid.UUID { return w.requestID }

// ErrInvalidWorkspaceRoot is returned by AllocateWorkspace when the root
// argument is empty, relative, or contains a parent-directory traversal
// sequence.
var ErrInvalidWorkspaceRoot = errors.New("runner: invalid sandbox root")

// ErrInvalidRequestID is returned when AllocateWorkspace receives the
// zero-value uuid.UUID (which a misconfigured caller could otherwise
// reuse, defeating Property 39 uniqueness).
var ErrInvalidRequestID = errors.New("runner: invalid request id")

// ErrWorkspaceIsolationViolation is returned by Verify when the supplied
// path does not match the workspace's recorded path.
//
// The Wave C orchestrator routes this error through the
// WorkspaceObserver hook so the metrics collector can increment
// goboxd_workspace_isolation_violation_total without internal/runner
// importing internal/metrics directly (architecture §5 dep graph).
var ErrWorkspaceIsolationViolation = errors.New("runner: workspace isolation violation")

// WorkspaceIsolationError carries the structured fields the Wave C
// orchestrator emits in its ERROR log entry (REQ A-24.5).
type WorkspaceIsolationError struct {
	RequestID uuid.UUID
	Expected  string
	Received  string
}

// Error implements error.
func (e *WorkspaceIsolationError) Error() string {
	return fmt.Sprintf("runner: workspace isolation violation: request_id=%s expected=%s received=%s",
		e.RequestID, e.Expected, e.Received)
}

// Is supports errors.Is(err, ErrWorkspaceIsolationViolation).
func (e *WorkspaceIsolationError) Is(target error) bool {
	return target == ErrWorkspaceIsolationViolation
}

// WorkspaceObserver is the hook the orchestrator wires when an
// isolation violation fires. It exists so the runner can notify the
// metrics collector without importing it directly. The default
// observer is the no-op nopObserver below; tests inject a recording
// observer to assert the violation surface.
type WorkspaceObserver interface {
	OnIsolationViolation(WorkspaceIsolationError)
}

// nopObserver is the default observer; it discards every event. The
// orchestrator overrides this in Wave C; tests inject a recording stub.
type nopObserver struct{}

func (nopObserver) OnIsolationViolation(WorkspaceIsolationError) {}

// AllocateWorkspace creates a new Sandbox_Job_Directory under root and
// records its identity for later verification.
//
// root MUST be an absolute, traversal-free path; the directory is
// created with os.Mkdir(... 0o700) so unprivileged users on the host
// cannot peek at the workspace contents. The per-job directory name is
// `job-<UUIDv4>` where UUIDv4 is the request id. A collision (a
// directory with the same name already exists) returns the underlying
// fs error rather than silently reusing the directory — the caller
// should treat this as a fatal startup state, since UUIDv4 collisions
// are astronomically unlikely.
//
// Property 39 callers note: the request id MUST be a fresh UUIDv4
// generated by the run handler from a cryptographically secure source.
// AllocateWorkspace itself does not generate the id — that decision is
// the run handler's so the same id can flow into request-scoped log
// entries and the response envelope.
func AllocateWorkspace(root string, requestID uuid.UUID) (*Workspace, error) {
	if err := validateRoot(root); err != nil {
		return nil, err
	}
	if requestID == uuid.Nil {
		return nil, ErrInvalidRequestID
	}

	// Ensure the root exists. Mode 0o755 is conservative: an operator
	// who pre-created the root with stricter perms (e.g. 0o775 group
	// write) is left untouched because os.MkdirAll is a no-op when the
	// directory already exists.
	if err := os.MkdirAll(root, 0o755); err != nil {
		return nil, fmt.Errorf("runner: create sandbox root %s: %w", root, err)
	}

	jobDir := filepath.Join(root, "job-"+requestID.String())
	if err := os.Mkdir(jobDir, 0o700); err != nil {
		return nil, fmt.Errorf("runner: allocate workspace %s: %w", jobDir, err)
	}

	return &Workspace{
		path:      filepath.Clean(jobDir),
		requestID: requestID,
	}, nil
}

// validateRoot enforces the documented preconditions on the sandbox
// root path: non-empty, absolute, and free of `..` traversal segments.
//
// The check inspects the raw path-segment sequence BEFORE filepath.Clean
// collapses it. A pre-clean traversal sequence indicates the operator
// configured a root that resolves to an unintended location once the
// kernel walks the path; rejecting it at startup forces the operator to
// pass the canonical absolute path explicitly.
func validateRoot(root string) error {
	if strings.TrimSpace(root) == "" {
		return fmt.Errorf("%w: empty path", ErrInvalidWorkspaceRoot)
	}
	if !filepath.IsAbs(root) {
		return fmt.Errorf("%w: %q is not absolute", ErrInvalidWorkspaceRoot, root)
	}
	for _, seg := range strings.Split(root, string(filepath.Separator)) {
		if seg == ".." {
			return fmt.Errorf("%w: %q contains parent traversal", ErrInvalidWorkspaceRoot, root)
		}
	}
	return nil
}

// Cleanup removes the workspace directory and its contents.
//
// Idempotent: calling Cleanup more than once returns nil even if the
// directory was already removed. Used by the deferred path in the run
// handler so cleanup can run from any termination mode (architecture
// REQ A-24.4) without bookkeeping.
func (w *Workspace) Cleanup() error {
	if w == nil || w.path == "" {
		return nil
	}
	err := os.RemoveAll(w.path)
	if err != nil {
		return fmt.Errorf("runner: cleanup %s: %w", w.path, err)
	}
	return nil
}

// Verify enforces the architecture §11 ownership invariant: every
// operation that writes to or removes a Sandbox_Job_Directory MUST first
// pass the path through Verify against the workspace it created.
//
// On match Verify returns nil. On mismatch it returns a
// *WorkspaceIsolationError (which satisfies errors.Is for
// ErrWorkspaceIsolationViolation) and notifies obs. obs may be nil; in
// that case nopObserver is used so callers don't need to special-case
// the unwired path.
func (w *Workspace) Verify(target string, obs WorkspaceObserver) error {
	if obs == nil {
		obs = nopObserver{}
	}
	if w == nil {
		viol := WorkspaceIsolationError{Expected: "", Received: target}
		obs.OnIsolationViolation(viol)
		return &viol
	}
	expected := filepath.Clean(w.path)
	received := filepath.Clean(target)
	if expected != received {
		viol := WorkspaceIsolationError{
			RequestID: w.requestID,
			Expected:  expected,
			Received:  received,
		}
		obs.OnIsolationViolation(viol)
		return &viol
	}
	return nil
}
